# Site settings
title: Jai Maa Gange Homestay
email: your-email@example.com
description: >-
  Welcome to our cozy homestay where comfort meets authentic local experience.
  Your home away from home in a peaceful setting.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

# Build settings
remote_theme: mmistakes/minimal-mistakes@4.24.0
plugins:
  - jekyll-remote-theme
  - jekyll-feed
  - jekyll-include-cache

# Minimal Mistakes theme settings
minimal_mistakes_skin: "air" # "air", "aqua", "contrast", "dark", "dirt", "neon", "mint", "plum", "sunrise"
locale: "en-US"
search: true

# Site Author
author:
  name: "Jai Maa Gange Homestay"
  avatar: # path of avatar image, e.g. "/assets/images/bio-photo.jpg"
  bio: "Your home away from home in a peaceful setting"
  location: "Your Location"
  links:
    - label: "Email"
      icon: "fas fa-fw fa-envelope-square"
      url: "mailto:your-email@example.com"
    - label: "Facebook"
      icon: "fab fa-fw fa-facebook-square"
      url: "https://facebook.com"
    - label: "Instagram"
      icon: "fab fa-fw fa-instagram"
      url: "https://instagram.com"

# Theme settings
show_downloads: false
google_analytics:
github:
  is_project_page: false
