# Site settings
title: Serene Homestay
email: your-email@example.com
description: >-
  Welcome to our cozy homestay where comfort meets authentic local experience.
  Your home away from home in a peaceful setting.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

# Build settings
remote_theme: pages-themes/cayman@v0.2.0
plugins:
  - jekyll-remote-theme
  - jekyll-feed

# Theme settings
show_downloads: false
google_analytics:
github:
  is_project_page: false
